### ISSUE TITLE
Icons blurry in firefox

### ISSUE THREAD

**Issue by skeddles** [vikrum/kidpix#15]
For cross browser support you need to add both of these properties:

```
image-rendering: crisp-edges; 
image-rendering: pixelated;
```

**Comment by vikrum** [comment]
Thanks for the report (and fix)! Can you please verify it looks ok here: https://kidpix.neocities.org/ Will merge in the main branch with other fixes once verified.

**Comment by skeddles** [comment]
Yup, lookin good

**Comment by vikrum** [comment]
Thank you! I'll deploy it to the main sites and merge it in the this repos main branch with all the fixes I have queued up.
