### ISSUE TITLE
How to start a new file?

### ISSUE THREAD

**Issue by tyner** [vikrum/kidpix#17]
Apologies if this is a silly question but we could not figure out how to start a new drawing. Is there a user manual that talks about this?

**Comment by vikrum** [comment]
Hi Tyner,

If you go to the eraser tool (red bar/stick), you can select the TNT or Fade-Away eraser. Then click on the canvas to use the tool which will eraser everything.

I'll post a video later tonight too.

Thanks for the question!

**Comment by tyner** [comment]
Ah, got it. Thanks so much!
