### ISSUE TITLE
Letter tool: characters not aligned to buttons

### ISSUE THREAD

**Issue by yaomtc** [vikrum/kidpix#2]
The characters should probably be centered within the buttons you push to select the letters? In Firefox they are quite badly off-center and in Chromium they are better, but still sitting on the bottom edge of the button.

Firefox: 
![firefox](https://user-images.githubusercontent.com/5534045/128288483-a0361937-25df-40e3-bf70-112ccae83e82.png)

Chromium:
![chromium](https://user-images.githubusercontent.com/5534045/128288484-43254b76-ab3c-4fa4-8c0b-ba4c98eaff76.png)

**Comment by liamr** [comment]
@vikrum Looks great for me in Firefox MacOS 91.0b9 - and thank you for the memories!
