### ISSUE TITLE
Missing tool: drip paint

### ISSUE THREAD

**Issue by vikrum** [vikrum/kidpix#20]
Ref impl: Always puts a drip at first mouse down, random time based intervals follow. Drip size same. Drip length randomly varies from 0 to 16px. Line width 5px. Modifier key makes drip longer.

![](https://user-images.githubusercontent.com/291215/129075092-dcc5ec51-9d96-4fa7-9d5b-82cc1822cdea.png)

**Comment by wartmanm** [comment]
kidpix.app seems to have this implemented?

**Comment by vikrum** [comment]
@wartmanm You're right! I haven't merged my local changes to the public repo in a while 😬 Thanks for the ping/reminder!
