### ISSUE TITLE
Rainbow Circle Texture

### ISSUE THREAD

**Issue by Harrison-Mitchell** [vikrum/kidpix#3]
Great implementation, thanks for the memories!
Noticed something with the "Texture ?" circle tool where the rainbow "spread" isn't evenly distributed based on the cursor draw angle.
Here are 5 circles in order from left to right, line added for visual axis of drag path:

- Dragged from top to bottom (0 degrees)
- Dragged from left-center top (30 degrees)
- Dragged from top left (45 degrees)
- Dragged from upper-left (60 degrees)
- Dragged from left to right (90 degrees)

![image](https://user-images.githubusercontent.com/17722100/128340120-464cb24f-a516-400f-9d07-df3e59e7d493.png)

Latest Linux Firefox for the record. (and assuming this isn't a bug in the original)

**Comment by vikrum** [comment]
Yeah, it uses the mouse position to squeeze the gradient. The og Kid Pix didn't really have this, but I sorta just eye balled it and kinda like it. What would you want to happen instead?

**Comment by Harrison-Mitchell** [comment]
As a user going into it blind I expected it to be an even distribution like the first circle on the left, no matter how / what angle it's drawn; if it was intentional than keep it as is by all means :)

**Comment by vikrum** [comment]
All good & thank you for the note though! I appreciate it :)
