### ISSUE TITLE
Bug: Firecracker eraser conflicts with persistence if the user closes the window/tab

### ISSUE THREAD

**Issue by ohheyjosh** [vikrum/kidpix#4]
It looks like the app uses some type of persistence to keep your work if you close the tab or window, but this is conflicting with the firecracker tool if the user exits mid-explosion:

![CleanShot 2021-08-05 at 11 24 36](https://user-images.githubusercontent.com/19754380/128376533-874c79d3-5219-4933-878f-cfb6b4287c20.png)

Steps to reproduce:
1. Create a masterpiece
2. Select firecracker tool from eraser menu
3. Apply firecracker to canvas, starting animation sequence
4. Close the browser tab or window before the animation sequence completes
5. Reopen browser tab or window

Possible solution: clearing the persistence state at the start of the firecracker animation sequence?

**Comment by bennett4senate** [comment]
I remember clearly when my friends and I discovered the "secret" that you could pause the firecracker (and other erase functions) mid-erase by pressing a certain button (spacebar maybe?). It seems like @ohheyjosh found it :) 
I came here to ask that functionality to be restored. Not sure if I should create this as a separate issue?

**Comment by vikrum** [comment]
Yep, you're both correct! @bennett4senate , you're memory is correct :) I'm part way thru implementing pausing it so that the animation is kept. It'll either be ctrl/alt or one of those modifier keys. I'll get it out later today.

I hope you're enjoying it!

**Comment by vikrum** [comment]
Deployed pausing the animation! Press Ctrl/Meta to stop it part way thru :)

**Comment by ohheyjosh** [comment]
Is that deployment live? The steps I described at the top can still be used to reproduce what feels like a bug and not a feature.
