### ISSUE TITLE
Lollipop tool wipes canvas

### ISSUE THREAD

**Issue by privatenumber** [vikrum/kidpix#5]
It's hard to reproduce, but when using the lollipop tool a few times, it accidentally wipes the entire canvas. I believe this is a bug.

Video:
https://recordit.co/OOhU99msZ3

**Comment by vikrum** [comment]
Hm, that's not good. Thank you for the report and video! I'll take a look and fix it.

**Comment by clarjon1** [comment]
I can replicate this behaviour in latest firefox on win10

**Comment by vikrum** [comment]
I was able to find a repro: mousedown, drag effect outside of canvas, re-enter, mouseup. Canvas get wiped. Will take a look at fixing it. Thanks again for the report!

**Comment by vikrum** [comment]
Fixed.
