### ISSUE TITLE
Rectangle with shift then other modifier like alt and shift no longer works

### ISSUE THREAD

**Issue by rofrol** [vikrum/kidpix#6]

**Comment by vikrum** [comment]
Browser/OS? What're you seeing on your side? I can't seem to repro it. 

Here is 1) no modifier, 2) w/ alt/command to remove border, and 3) shift+alt to make it a square with no border:

![Screen Shot 2021-08-06 at 9 46 35 AM](https://user-images.githubusercontent.com/291215/128544462-42eaf466-61fe-4823-aa61-49a257b21a28.png)

**Comment by rofrol** [comment]
Cannot reproduce anymore. Closing.
